---
modes:
  titling:
    name: Titling
    key: "ctrl + shift - 1"
  switch_app:
    name: Switch
    key: "ctrl - ;"
  quit:
    name: Quit
    key: "ctrl - q"
  slack:
    name: Slack
    key: "ctrl + cmd + shift + alt - s"
    apps: ["slack"]
    key_maps:
      "p":
        to: "cmd - k"
      "g":
        to: "cmd - g"
      "shift - h":
        to: "ctrl - 1"
      "d":
        to: "ctrl - 2"
      "a":
        to: "ctrl - 3"
      "shift - e":
        to: "cmd - UP"
      "t":
        to: "cmd + shift - t"
      "h":
        to: "LEFT"
      "j":
        to: "DOWN"
      "k":
        to: "UP"
      "l":
        to: "DOWN"
  yabai:
    name: Yabai
    key: "ctrl - y"
  mouse:
    name: Mouse
    key: "ctrl - m"
  short_cat:
    name: Cat
    key: "ctrl - o"
  intellij:
    name: "IntellJ"
    key: "ctrl + cmd + shift + alt - i"
    key_maps:
      "ctrl - h": 
        to: ctrl  + alt - LEFT
      "ctrl - j":
        to: ctrl  + alt - DOWN
      "ctrl - k":
        to: ctrl  + alt - UP
      "ctrl - l":
        to: ctrl  + alt - RIGHT

    apps: ["intellij"]
  default:
    name: "-"
    key: "ctrl - 0"

app_specifics:
  "ctrl - w":
      - app: intellij
        mode: intellij
  "ctrl - s":
      - app: slack
        mode: slack


apps:
  chrome:
    name: Google Chrome
    key: c
  slack:
    name: Slack
    key: s
  terminal:
    name: Terminal
    key: t
  intellij:
    name: IntelliJ IDEA
    app: IntelliJ IDEA CE
    key: i
  activity:
    name: Activity Monitor
    app: Activity Monitor
    key: a

xbar:
  skhd_mode:
    file: skhd_mode
