#!/bin/zsh
#
cws (){
  BASE_WS="$HOME/workspace/projects"
  DES="$1"
  ABS_PATH="$BASE_WS/$DES"
  MAIN="main"

  if [ ! -d "$ABS_PATH" ]
  then
    echo "Folder [$ABS_PATH] does not exist"
    return 1
  fi

  if ! ( tmux ls | grep -q "$MAIN" )
  then
    echo "Create new $MAIN session"
    tmux new -s $MAIN -d -c $ABS_PATH -n $DES
  fi

  if ! ( tmux list-windows -t $MAIN -F "#{window_name}" | grep -x "$DES" )
  then
    echo "Create new windows $DES"
    tmux new-window -t $MAIN -n $DES -c $ABS_PATH
  fi

  if [[ "$TMUX" = "" ]]
  then
    echo "Tmux: attach session [$MAIN]"
    tmux attach -t $MAIN\; select-window -t $DES
  else
    echo "Tmux: jump to window [$DES]"
    tmux select-window -t $DES
  fi
}

xbar_refresh () {
  open -gj "xbar://app.xbarapp.com/refreshPlugin?path=$1"
}

skhd_mode () {
  echo $1 > /tmp/skhd_mode
  xbar_refresh skhd_mode
}

xbar_yabai_refresh () {
  xbar_refresh yabai
}
