export ZSH=$(ls -d ~/.oh-my-zsh)
ZSH_THEME="cloud"
plugins=(git)
source $ZSH/oh-my-zsh.sh
export DOTFILES="$HOME/.dotfiles"
source $DOTFILES/khiemnsrc
source $DOTFILES/zsh/auto_complete

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
